In [1]:
import tensorflow as tf
import numpy as np

In [2]:
locations = tf.constant([[12.97, 75.58],
                         [13.31, 75.77]],
                        dtype=tf.float16,
                        name="locations")
locations.shape, locations.ndim, locations

2022-01-17 14:22:43.619342: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


(TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[12.97, 75.56],
        [13.31, 75.75]], dtype=float16)>)

2022-01-17 14:22:43.629865: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-17 14:22:43.630455: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-17 14:22:43.631813: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-17 14:22:43.632672: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zer

In [5]:
locations + 10

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[22.97, 85.56],
       [23.31, 85.75]], dtype=float16)>

In [6]:
locations - 10

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 2.969, 65.56 ],
       [ 3.312, 65.75 ]], dtype=float16)>

In [7]:
tf.add(locations, 10)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[22.97, 85.56],
       [23.31, 85.75]], dtype=float16)>

In [8]:
locations*2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 25.94, 151.1 ],
       [ 26.62, 151.5 ]], dtype=float16)>

In [9]:
# Tf. multiply uses the element wise multiplication
# Use when multiplying the matrices with the scalars
tf.multiply(locations, 2)


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 25.94, 151.1 ],
       [ 26.62, 151.5 ]], dtype=float16)>

In [13]:
# Element Wise multiplication
print(locations)
locations*locations

tf.Tensor(
[[12.97 75.56]
 [13.31 75.75]], shape=(2, 2), dtype=float16)


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 168.2, 5708. ],
       [ 177.2, 5740. ]], dtype=float16)>

In [10]:
# Tf.matmul uses the matrix multiplication 
# Use when multiplying the matrices with the matrices
tf.matmul(locations, locations)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1174., 6704.],
       [1181., 6744.]], dtype=float16)>

In [12]:
# Similar to matrix multiplication, the @ symbol does the matrix multiplication
locations @ locations

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1174., 6704.],
       [1181., 6744.]], dtype=float16)>

In [14]:
A = tf.constant([[1,2,3],
                [4,5,6]])
print(A, A.shape, A.ndim)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) (2, 3) 2


In [17]:
B = tf.constant([[1,2], [3,4],[5,6]])
print(B, B.shape,B.ndim)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) (3, 2) 2


In [18]:
A @ B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [19]:
tf.matmul(A, B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [21]:
C = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
C

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [22]:
tf.matmul(A, C)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

tf.matmul(B, C)
# Will fail as multiplication between 3x2 & 3x3
# The inner columns count must match

In [29]:
res = tf.matmul(tf.reshape(B, shape=(2,3)), C)
print(res, tf.reshape(B, shape=(2,3)).shape, C.shape)

tf.Tensor(
[[30 36 42]
 [66 81 96]], shape=(2, 3), dtype=int32) (2, 3) (3, 3)


In [32]:
B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [31]:
tf.reshape(B, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [28]:
tf.transpose(B)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [30]:
res2 = tf.matmul(tf.transpose(B), C)
print(res, tf.transpose(B).shape,  C.shape)


tf.Tensor(
[[30 36 42]
 [66 81 96]], shape=(2, 3), dtype=int32) (2, 3) (3, 3)


##### Use Transpose ( flip the axes) rather than reshape

In [50]:
# Finding the max, min, stadard deviation, variance
P = tf.constant(np.arange(-30, 30), name="Points")
print(P, tf.abs(P))

tf.Tensor(
[-30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15 -14 -13
 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5
   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23
  24  25  26  27  28  29], shape=(60,), dtype=int64) tf.Tensor(
[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7
  6  5  4  3  2  1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17
 18 19 20 21 22 23 24 25 26 27 28 29], shape=(60,), dtype=int64)


In [55]:
# Note the variance in the tensorflow probability library
import tensorflow_probability as tfp
# The standard deviation function uses the tensor of type float type
# The math library also has the variance 

# Minimum
print("Minimum : ", tf.reduce_min(P))
# Maximum
print("Maximum : ", tf.reduce_max(P))
# Sum
print("Sum : ", tf.reduce_sum(P))
# Mean
print("Mean : ", tf.reduce_max(P))

# Variance
print("Variance : ", tfp.stats.variance(P))
# Variance in the math lib
print("Math Variance : ", tf.math.reduce_variance(tf.cast(P, dtype=tf.float16)))

# Standard Deviation
print("Math : Standard Deviation : ", tf.math.reduce_std(tf.cast(P, dtype=tf.float16)))


Minimum :  tf.Tensor(-30, shape=(), dtype=int64)
Maximum :  tf.Tensor(29, shape=(), dtype=int64)
Sum :  tf.Tensor(-30, shape=(), dtype=int64)
Mean :  tf.Tensor(29, shape=(), dtype=int64)
Variance :  tf.Tensor(300, shape=(), dtype=int64)
Variance :  tf.Tensor(299.8, shape=(), dtype=float16)
Standard Deviation :  tf.Tensor(17.31, shape=(), dtype=float16)


In [61]:
# positional max, min
tf.random.set_seed(100)
Q = tf.random.shuffle(P)
print(Q)

tf.Tensor(
[-22 -20  26  21  -7   7  17 -18 -23  15  18   6 -26  -6   0  -4  29  11
  25  -8 -27 -19  24  12  -9 -12  -1 -21  10 -30  27  14  -3  28   2  22
 -13 -14 -16 -15   4 -28  23  19  16   3 -24 -11 -10   5  -2 -25 -17   8
   1 -29  20   9  13  -5], shape=(60,), dtype=int64)


In [67]:
print("Max Position is :: ",tf.argmax(Q), )
print("Max Value is :: ",Q[16])
print(Q[tf.argmax(Q)] == tf.reduce_max(Q))

Max Position is ::  tf.Tensor(16, shape=(), dtype=int64)
Max Value is ::  tf.Tensor(29, shape=(), dtype=int64)
tf.Tensor(True, shape=(), dtype=bool)


In [69]:
print("Min Position is :: ",tf.argmin(Q), )
print("Min Value is :: ",Q[29])
print(Q[tf.argmin(Q)] == tf.reduce_min(Q))

Min Position is ::  tf.Tensor(29, shape=(), dtype=int64)
Min Value is ::  tf.Tensor(-30, shape=(), dtype=int64)
tf.Tensor(True, shape=(), dtype=bool)


In [77]:
# Squeezing Tensors
tf.random.set_seed(80)
G = tf.constant(tf.random.normal(shape=[50]), shape=(1,1,1,50))
print(G, G.ndim, G.shape)
# Squeezing ( Removing the single dimension tensors)
G_squeezed = tf.squeeze(G)
print(G_squeezed)

tf.Tensor(
[[[[-0.01728362 -1.1931074  -0.43164262 -0.27097437 -0.2553166
    -0.6153051   0.75505924 -1.4303387   2.5166614   0.00741944
     0.57688767 -2.023734    1.1158017   0.12886627 -0.13360472
     0.47684544  0.48761976  1.5617888   0.5189699  -0.06123443
    -0.59523624 -0.5900524   0.5511933  -0.4449501  -1.2182286
    -1.407972    0.29299062 -0.897691    0.18440363  1.597959
    -0.5355442   0.7986791  -2.0907233  -1.5609344  -0.21828228
     0.55202174  0.39911115  2.4980643  -1.4632348   0.08087946
     1.0713995  -0.6494796  -0.3699775   0.06696595  0.50597364
    -1.1123779  -0.646951    0.07662649 -1.8027563   1.0992827 ]]]], shape=(1, 1, 1, 50), dtype=float32) 4 (1, 1, 1, 50)
tf.Tensor(
[-0.01728362 -1.1931074  -0.43164262 -0.27097437 -0.2553166  -0.6153051
  0.75505924 -1.4303387   2.5166614   0.00741944  0.57688767 -2.023734
  1.1158017   0.12886627 -0.13360472  0.47684544  0.48761976  1.5617888
  0.5189699  -0.06123443 -0.59523624 -0.5900524   0.5511933  -0.444950

### One hot encoding tensors
 A one hot encoding is a representation of categorical variables as binary vectors. 
 This first requires that the categorical values be mapped to integer values. 
 Then, each integer value is represented as a binary vector that is all zero values except the index of the integer, which is marked with a 1


In [80]:
item_labels = ["shoes", "belt", "shirt", "cap", "sneakers"]
items =       [0, 1, 2, 3, 4]
items_one_hot = tf.one_hot(items, depth=len(items))
items_one_hot

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [82]:
tf.one_hot(items, depth=len(items), on_value="yay", off_value="!")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'yay', b'!', b'!', b'!', b'!'],
       [b'!', b'yay', b'!', b'!', b'!'],
       [b'!', b'!', b'yay', b'!', b'!'],
       [b'!', b'!', b'!', b'yay', b'!'],
       [b'!', b'!', b'!', b'!', b'yay']], dtype=object)>

In [83]:
H = tf.range(0, 10)
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [88]:
print("Square :  : ", tf.square(H))
print("Squareoot : ", tf.sqrt(tf.cast(H,dtype=tf.float16)))
print("log : ", tf.math.log(tf.cast(H,dtype=tf.float16)))


Square :  :  tf.Tensor([ 0  1  4  9 16 25 36 49 64 81], shape=(10,), dtype=int32)
Squareoot :  tf.Tensor([0.    1.    1.414 1.732 2.    2.236 2.45  2.646 2.828 3.   ], shape=(10,), dtype=float16)
log :  tf.Tensor([  -inf 0.     0.6934 1.099  1.387  1.609  1.792  1.946  2.08   2.197 ], shape=(10,), dtype=float16)


In [90]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
##### End of notes