In [1]:
import tensorflow as tf
import numpy as np

In [2]:
locations = tf.constant([[12.97, 75.58],
                         [13.31, 75.77]],
                        dtype=tf.float16,
                        name="locations")
locations.shape, locations.ndim, locations

2022-01-17 14:22:43.619342: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


(TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[12.97, 75.56],
        [13.31, 75.75]], dtype=float16)>)

2022-01-17 14:22:43.629865: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-17 14:22:43.630455: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-17 14:22:43.631813: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-17 14:22:43.632672: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zer

In [5]:
locations + 10

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[22.97, 85.56],
       [23.31, 85.75]], dtype=float16)>

In [6]:
locations - 10

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 2.969, 65.56 ],
       [ 3.312, 65.75 ]], dtype=float16)>

In [7]:
tf.add(locations, 10)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[22.97, 85.56],
       [23.31, 85.75]], dtype=float16)>

In [8]:
locations*2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 25.94, 151.1 ],
       [ 26.62, 151.5 ]], dtype=float16)>

In [9]:
# Tf. multiply uses the element wise multiplication
# Use when multiplying the matrices with the scalars
tf.multiply(locations, 2)


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 25.94, 151.1 ],
       [ 26.62, 151.5 ]], dtype=float16)>

In [13]:
# Element Wise multiplication
print(locations)
locations*locations

tf.Tensor(
[[12.97 75.56]
 [13.31 75.75]], shape=(2, 2), dtype=float16)


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 168.2, 5708. ],
       [ 177.2, 5740. ]], dtype=float16)>

In [10]:
# Tf.matmul uses the matrix multiplication 
# Use when multiplying the matrices with the matrices
tf.matmul(locations, locations)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1174., 6704.],
       [1181., 6744.]], dtype=float16)>

In [12]:
# Similar to matrix multiplication, the @ symbol does the matrix multiplication
locations @ locations

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1174., 6704.],
       [1181., 6744.]], dtype=float16)>

In [14]:
A = tf.constant([[1,2,3],
                [4,5,6]])
print(A, A.shape, A.ndim)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) (2, 3) 2


In [17]:
B = tf.constant([[1,2], [3,4],[5,6]])
print(B, B.shape,B.ndim)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) (3, 2) 2


In [18]:
A @ B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [19]:
tf.matmul(A, B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [21]:
C = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
C

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [22]:
tf.matmul(A, C)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

tf.matmul(B, C)
# Will fail as multiplication between 3x2 & 3x3
# The inner columns count must match

In [29]:
res = tf.matmul(tf.reshape(B, shape=(2,3)), C)
print(res, tf.reshape(B, shape=(2,3)).shape, C.shape)

tf.Tensor(
[[30 36 42]
 [66 81 96]], shape=(2, 3), dtype=int32) (2, 3) (3, 3)


In [32]:
B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [31]:
tf.reshape(B, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [28]:
tf.transpose(B)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [30]:
res2 = tf.matmul(tf.transpose(B), C)
print(res, tf.transpose(B).shape,  C.shape)


tf.Tensor(
[[30 36 42]
 [66 81 96]], shape=(2, 3), dtype=int32) (2, 3) (3, 3)


##### Use Transpose ( flip the axes) rather than reshape

##### End of notes